from spooky_crawler.middleware.article_classifier import Weighting
from spooky_crawler.helpers.spooky_classifications import ArticleClass

# keywords must be lowercase!

# regex matches from the top of the list.
# if a single term is present in any other keywords with 2+ terms
# ensure the 2+ terms come before the single term. Otherwise the single term will
# be counted but not the 2+ terms.
_common_weights = {
    'paranormal': 0.5,
    'supernatural': 0.5,
    'natural': -0.1,
    'fans': -0.1,
    'things': -0.1,
    'soap': -0.5,
    'frightfest': -0.5,
    'solved': -0.5,
    'movie': -0.5,
    'movies': -0.5,
    'musical': -0.5,
    'tv': -1,
    'virtual': -1,
    'performance': -1,
    'halloween': -1,
    'hallowe\'en': -1,
    'hallowe’en': -1,
    'crimestoppers': -1,
    'hoax': -1,
    'list': -1,
    'abuse': -1,
    'zombie knife': -1,
    'zombie knives': -1,
}

ghost_weighting = Weighting({
    'rolls royce': -1,
    'silver ghost': -1,
    'ghost town': -1,
    'ghost towns': -1,
    'ghost street': -1,
    'ghost streets': -1,
    'ghost world': -1,
    'ghost fishing': -1,
    'ghost net': -1,
    'ghost nets': -1,
    'ghost station': -1,
    'ghosts in the machine': -1,
    'ghost shark': -1,
    'ghost sharks': -1,
    'ghost train': -1,
    'ghost trains': -1,
    'fish': -1,
    'white as a ghost': 0,
    'time slip': 1,
    'apparition': 1,
    'paranormal investigator': 1,
    'haunted': 0.8,
    'seance': 0.5,
    'manifestations': 1,
    'manifestation': 1,
    'ghosts': 1,
    'ghost': 1,
    'old haunt': 0,
    'haunt': 1,
    **_common_weights},
    ArticleClass.GHOST.value)

ufo_weighting = Weighting({
    'ufo': 1,
    'ufos': 1,
    'uap': 1,
    'uaps': 1,
    'flying saucer': 0.8,
    'flying saucers': 0.8,
    'black triangle diversion': -1,
    'black triangle': 1,
    'alien': 1,
    'extraterrestrial': 1,
    'cloud': -1,
    'monument': -1,
    'illegal': -1,
    'pyrotechnic': -1,
    'memorial': -1,
    'tribute': -1,
    'perfume': -1,
    **_common_weights},
    ArticleClass.UFO.value)

abc_weighting = Weighting({
    'big-foot': 1,
    'big foot': 1,
    'bigfoot': 1,
    'yeti': 1,
    'sasquatch': 1,
    'big cat': 1,
    'cryptid': 1,
    'cryptozoology': 1,
    'mystery creature': 1,
    'mystery beast': 1,
    'fairy folk': 1,
    'fairy': 0.5,
    'puma': 0.5,
    'panther': 0.5,
    'lion': 0.5,
    'gnome': 0.2,
    'sighting': 0.2,
    **_common_weights},
    ArticleClass.ABC.value)
