from spooky_crawler.middleware.article_classifier import Weighting
from spooky_crawler.helpers.spooky_classifications import ArticleClass

# keywords must be lowercase!

# regex matches from the top of the list.
# if a single term is present in any other keywords with 2+ terms
# ensure the 2+ terms come before the single term. Otherwise the single term will
# be counted but not the 2+ terms.
_common_weights = {
    'paranormal': 1,
    'supernatural': 1,
    'natural': -1,
    'solved': -2,
    'film': -2,
    'films': -2,
    'movie': -2,
    'movies': -2,
    'musical': -2,
    'tv': -2,
    'virtual': -2,
    'fans': -0.5,
    'soap': -1,
    'performance': -1,
    'frightfest': -1,
    'things': -10,
    'halloween': -10,
    'hallowe\'en': -10,
    'hallowe’en': -10,
    'crimestoppers': -10,
    'hoax': -100,
    'list': -100,
    'abuse': -100,
}

ghost_weighting = Weighting({
    'rolls royce': -4,
    'silver ghost': -4,
    'ghost town': -4,
    'ghost towns': -4,
    'ghost street': -4,
    'ghost streets': -4,
    'ghost world': -4,
    'ghost fishing': -4,
    'ghost net': -4,
    'ghost nets': -4,
    'ghost station': -4,
    'ghosts in the machine': -4,
    'ghost shark': -4,
    'ghost sharks': -4,
    'ghost train': -4,
    'ghost trains': -4,
    'fish': -1,
    'white as a ghost': 0,
    'time slip': 2,
    'apparition': 2,
    'paranormal investigator': 2,
    'haunted': 1,
    'seance': 1,
    'ghosts': 1,
    'manifestations': 0.5,
    'manifestation': 0.5,
    'ghost': 0.5,
    'spirt': 0.5,
    'haunt': 0.5,
    **_common_weights},
    ArticleClass.GHOST.value)

ufo_weighting = Weighting({
    'flying saucer': 1,
    'flying saucers': 1,
    'ufo': 1,
    'ufos': 1,
    'black triangle diversion': 0,
    'black triangle': 1,
    'alien': 0.5,
    'extraterrestrial': 0.5,
    'cloud': -1,
    'monument': -1,
    'illegal': -1,
    'pyrotechnic': -10,
    'memorial': -10,
    'tribute': -10,
    'perfume': -100,
    **_common_weights},
    ArticleClass.UFO.value)

weird_weighting = Weighting({
    'ghost ship': 2,
    'cryptid': 2,
    'cryptozoology': 1,
    'mystery creature': 1,
    'mystery beast': 1,
    'big cat': 0.5,
    'zombie knife': -100,
    'zombie knives': -100,
    'zombie': 0.5,
    'odd': 0.5,
    'puma': 0.2,
    'panther': 0.2,
    'weird': 0.2,
    'mystery': 0.1,
    'creepy': 0.1,
    **_common_weights},
    ArticleClass.WEIRD.value)
